name: collectpay
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  http: ^0.13.4
  connectivity: ^3.0.6
  flutter_observable_state: ^1.3.0
  flutter_easyloading: ^3.0.3
  share: ^2.0.4
  smooth_star_rating: 1.1.1
  qr_flutter: ^4.0.0
  pin_code_fields: ^7.3.0
  geolocator: ^8.2.0
  dio: ^4.0.4
  google_maps_flutter: ^2.1.1
  group_radio_button: ^1.2.0
  geocoding: ^2.0.2
  permission_handler: ^9.2.0
  image_picker: ^0.8.4+9
  contacts_service: ^0.6.3
  bottom_navy_bar: ^6.0.0
  qrscan: ^0.3.2
  persistent_bottom_nav_bar: ^4.0.2
  flutter_dialpad: ^1.0.4
  webview_flutter: ^3.0.2
  path_provider: ^2.0.9
  file_utils: ^1.0.1
  date_format: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#bottom_navy_bar: ^6.0.0
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - images/onboarding_one.png
    - images/shop_icon.png
    - images/qr_icon.png
    - images/card_icon.png
    - images/location_icon.png
    - images/add_icon.png
    - images/send_icon.png
    - images/back_icon.png
    - images/onboarding_two.png
    - images/onboarding_three.png
    - images/onboarding_four.png
    - images/onboarding_five.png
    - images/onboarding_card.png
    - images/wellcome_image.png
    - images/collect_pay_logo.png
    - images/ic_about_us.png
    - images/ic_invite_friends.png
    - images/ic_notification.png
    - images/ic_payment.png
    - images/ic_logout.png
    - images/ic_reward_credits.png
    - images/ic_promo_code.png
    - images/ic_settings.png
    - images/ic_qr_code.png
    - images/ic_support.png
    - images/ic_search.png
    - images/ic_shopping_cart.png
    - images/ic_user_profile.png
    - images/right_new_arrow_icon.png
    - images/my_home_big.png
    - images/budget_icon.png
    - images/gasoline_icon.png
    - images/category_banner_icon.png
    - images/gasolin_icon.png
    - images/gasoline_banner_icon.png
    - images/my_wallet_icon.png
    - images/payment_icon.png
    - images/product_banner_icon.png
    - images/qr_code_scan_icon.png
    - images/qr_code_scanner.png
    - images/super_market_icon.png
    - images/supermarket_banner_icon.png
    - images/category_icon.png
    - images/product_icon.png
    - images/send_money_icon.png
    - images/transaction_icon.png
    - images/check_balance_icon.png
    - images/recharge_icon.png
    - images/ic_refer_friends_bg.jpg
    - images/dialer_icon.png
    - images/card_inactive.png
    - images/download_invoice.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
